#!/usr/bin/env bash
# lifecycle-check.sh — assert that every code anchor (path:line) cited by the domain-reference skill
# still points at the code it was written about. Anchors cover the event lifecycle, the glossary and
# the misconceptions; each one is pinned in scripts/anchors.tsv as <citation><TAB><expected text>.
#
# Usage (from anywhere inside the lago repo):
#   .claude/skills/domain-reference/scripts/lifecycle-check.sh            # check, print problems + summary
#   .claude/skills/domain-reference/scripts/lifecycle-check.sh -v         # also print every OK anchor
#   .claude/skills/domain-reference/scripts/lifecycle-check.sh --emit     # print a fresh anchors.tsv to stdout
#   .claude/skills/domain-reference/scripts/lifecycle-check.sh --table F  # check against another table (e.g. a
#                                                                         # scratch copy while testing)
#
# Citation forms understood (as written in SKILL.md and reference/*.md):
#   events-processor/<path>:<line>[-<line>]   repo-relative (also docs/..., connectors/..., .env...)
#   $API/<path>:<line>[-<line>]               lago-api at the pinned gitlink SHA, via
#                                             research-methodology's pinned-checkout.sh
# Checks:
#   OK          the cited (first) line contains the expected text
#   MOVED       the text is elsewhere in the file: the new line is printed (update the citation)
#   CHANGED     the text is nowhere in the file (re-read the code; the claim may be wrong now)
#   GONE        the cited file does not exist
#   UNASSERTED  a citation in the skill's markdown has no row in anchors.tsv (add one)
#   STALE       a row in anchors.tsv is no longer cited anywhere (remove it)
# --emit regenerates rows from the CURRENT code for every citation found in the markdown. Use it only
# after you have re-read each changed anchor yourself; it copies whatever the line says today.
#
# Read-only on the repo. Exit codes: 0 every anchor OK and the table matches the markdown;
#   1 at least one MOVED/CHANGED/GONE/UNASSERTED/STALE; 2 usage error or $API unavailable.
set -euo pipefail

usage() { awk 'NR>1 && /^#/ {print; next} NR>1 {exit}' "$0"; }
verbose=0 emit=0 table=""
while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -v|--verbose) verbose=1 ;;
    --emit) emit=1 ;;
    --table) shift; table="${1:?--table needs a file}" ;;
    *) echo "lifecycle-check: unknown option $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
skill="$(dirname "$here")"
[ -n "$table" ] || table="$here/anchors.tsv"
repo="$(git -C "$here" rev-parse --show-toplevel 2>/dev/null)" || { echo "lifecycle-check: not inside the lago repo" >&2; exit 2; }
API="$("$repo/.claude/skills/research-methodology/scripts/pinned-checkout.sh" api)" || {
  echo "lifecycle-check: could not obtain the pinned lago-api checkout (see research-methodology)" >&2; exit 2; }

# All citations in the skill's markdown, deduplicated, in first-seen order.
cite_re='(\$API/)?([A-Za-z0-9_.][A-Za-z0-9_./-]*)?(\.(go|rb|rake|md|yml|yaml|sql|json|toml|mod|sh|conf|default)|(Dockerfile|Gemfile)[A-Za-z.]*):[0-9]+(-[0-9]+)?'
citations() {
  find "$skill" -name '*.md' -type f | sort | while IFS= read -r f; do grep -oE "$cite_re" "$f" || true; done | awk '!seen[$0]++'
}

resolve() { # citation -> "abs_path<TAB>start<TAB>end"
  local c="$1" path lines start end
  path="${c%:*}"; lines="${c##*:}"; start="${lines%-*}"; end="${lines#*-}"
  case "$path" in
    '$API/'*) path="$API/${path#\$API/}" ;;
    *) path="$repo/$path" ;;
  esac
  printf '%s\t%s\t%s\n' "$path" "$start" "$end"
}

line_text() { # abs_path line -> trimmed text (tabs -> spaces, max 100 chars)
  sed -n "${2}p" "$1" | tr '\t' ' ' | sed -E 's/^ +//; s/ +$//' | cut -c1-100
}

if [ "$emit" -eq 1 ]; then
  printf '# citation\texpected text on the cited (first) line. Generated by lifecycle-check.sh --emit; review every row.\n'
  citations | while IFS= read -r c; do
    IFS=$'\t' read -r p s _ < <(resolve "$c")
    if [ -f "$p" ]; then printf '%s\t%s\n' "$c" "$(line_text "$p" "$s")"; else printf '%s\t%s\n' "$c" "<<MISSING FILE>>"; fi
  done
  exit 0
fi

[ -f "$table" ] || { echo "lifecycle-check: $table missing (generate with --emit after review)" >&2; exit 2; }

ok=0 bad=0
while IFS=$'\t' read -r c want; do
  case "$c" in ''|'#'*) continue ;; esac
  IFS=$'\t' read -r p s e < <(resolve "$c")
  if [ ! -f "$p" ]; then echo "GONE       $c"; bad=$((bad + 1)); continue; fi
  total="$(wc -l < "$p")"
  if [ "$e" -gt "$total" ] || [ "$s" -gt "$total" ]; then
    echo "CHANGED    $c (file has only $total lines)"; bad=$((bad + 1)); continue
  fi
  got="$(line_text "$p" "$s")"
  if [ -n "$want" ] && grep -qF -- "$want" <<< "$got"; then
    ok=$((ok + 1)); [ "$verbose" -eq 0 ] || echo "OK         $c"
    continue
  fi
  # Look for the expected text elsewhere in the file.
  new="$(tr '\t' ' ' < "$p" | sed -E 's/^ +//; s/ +$//' | cut -c1-100 | grep -nF -- "$want" | head -n1 | cut -d: -f1 || true)"
  if [ -n "$new" ]; then
    echo "MOVED      $c -> ${c%:*}:$new"
  else
    echo "CHANGED    $c (expected: $want | now: $got)"
  fi
  bad=$((bad + 1))
done < "$table"

# Coverage: markdown citations vs table rows. Here-strings, not `printf | grep -q`: under
# pipefail an early grep -q exit can SIGPIPE printf and turn a match into a false report.
cited="$(citations)"
rows="$(grep -vE '^(#|$)' "$table" | cut -f1)"
while IFS= read -r c; do
  [ -n "$c" ] || continue
  grep -qxF -- "$c" <<< "$rows" || { echo "UNASSERTED $c (cited in markdown, no row in anchors.tsv)"; bad=$((bad + 1)); }
done <<< "$cited"
while IFS= read -r c; do
  [ -n "$c" ] || continue
  grep -qxF -- "$c" <<< "$cited" || { echo "STALE      $c (row in anchors.tsv, not cited any more)"; bad=$((bad + 1)); }
done <<< "$rows"

echo "lifecycle-check: $ok anchors OK, $bad problem(s); events-processor @ $(git -C "$repo" rev-parse --short HEAD), lago-api @ $(git -C "$API" rev-parse --short HEAD)"
[ "$bad" -eq 0 ] || exit 1
exit 0
